server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      access: read_only

spring:
  application:
    name: fast-transfer
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${spring.application.name}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

app:
  currency-exchange-api:
    url: https://api.freecurrencyapi.com
    key: ${CURRENCY_EXCHANGE_API_KEY:default-key}

resilience4j:
  circuitbreaker:
    instances:
      currencyExchangeClient:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s

springdoc:
  api-docs:
    enabled: true
  show-actuator: false