TRUNCATE TABLE currency;

INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'EUR', 'Euro');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'USD', 'US Dollar');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'JPY', 'Japanese Yen');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'BGN', 'Bulgarian Lev');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'CZK', 'Czech Republic Koruna');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'DKK', 'Danish Krone');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'GBP', 'British Pound Sterling');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'HUF', 'Hungarian Forint');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'PLN', 'Polish Zloty');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'RON', 'Romanian Leu');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'SEK', 'Swedish Krona');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'CHF', 'Swiss Franc');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'ISK', 'Icelandic Króna');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'NOK', 'Norwegian Krone');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'HRK', 'Croatian Kuna');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'RUB', 'Russian Ruble');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'TRY', 'Turkish Lira');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'AUD', 'Australian Dollar');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'BRL', 'Brazilian Real');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'CAD', 'Canadian Dollar');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'CNY', 'Chinese Yuan');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'HKD', 'Hong Kong Dollar');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'IDR', 'Indonesian Rupiah');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'ILS', 'Israeli New Sheqel');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'INR', 'Indian Rupee');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'KRW', 'South Korean Won');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'MXN', 'Mexican Peso');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'MYR', 'Malaysian Ringgit');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'NZD', 'New Zealand Dollar');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'PHP', 'Philippine Peso');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'SGD', 'Singapore Dollar');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'THB', 'Thai Baht');
INSERT INTO currency (id, code, name) VALUES (nextval('currency_id_seq'), 'ZAR', 'South African Rand');
